// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaApp.Api.Data;

#nullable disable

namespace PizzaApp.Api.Migrations
{
    [DbContext(typeof(PizzaDbContext))]
    [Migration("20260928194550_CompletePizzeriaMenuSections")]
    partial class CompletePizzeriaMenuSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PizzaApp.Api.Models.CompletedOrderDay", b =>
                {
                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CollectorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPizzeria")
                        .HasColumnType("boolean");

                    b.Property<string>("OrdersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RestaurantId", "Date");

                    b.ToTable("CompletedOrderDays");
                });

            modelBuilder.Entity("PizzaApp.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MenuNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Pizzor",
                            Description = "Tomat, Ost",
                            MenuNumber = 1,
                            Name = "Margherita",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pizzor",
                            Description = "Skinka",
                            MenuNumber = 2,
                            Name = "Vesuvio",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pizzor",
                            Description = "Skinka, Champinjoner",
                            MenuNumber = 3,
                            Name = "Capricciosa",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Pizzor",
                            Description = "Skinka, Ananas",
                            MenuNumber = 4,
                            Name = "Hawaii",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = "Pizzor",
                            Description = "Skinka (Inbakad)",
                            MenuNumber = 5,
                            Name = "Calzone",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = "Pizzor",
                            Description = "Tonfisk, Lök",
                            MenuNumber = 6,
                            Name = "Pescatore",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = "Pizzor",
                            Description = "Köttfärs, Vitlökssås",
                            MenuNumber = 7,
                            Name = "Caruso",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pizzor",
                            Description = "Köttfärssås, Lök",
                            MenuNumber = 8,
                            Name = "Bolognese",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 13,
                            Category = "Pizzor",
                            Description = "Bacon, Lök",
                            MenuNumber = 9,
                            Name = "La Maffia",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 14,
                            Category = "Pizzor",
                            Description = "Salami",
                            MenuNumber = 10,
                            Name = "Cacciatore",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "Pizzor",
                            Description = "Skinka, Räkor",
                            MenuNumber = 11,
                            Name = "Tomaso",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 16,
                            Category = "Pizzor",
                            Description = "Musslor, Räkor",
                            MenuNumber = 12,
                            Name = "Marinara",
                            Price = 85m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 17,
                            Category = "Pizzor",
                            Description = "Skinka, Banan, Ananas, Curry",
                            MenuNumber = 13,
                            Name = "Africana",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 18,
                            Category = "Pizzor",
                            Description = "Skinka, Champinjoner, Räkor",
                            MenuNumber = 14,
                            Name = "Jamaica",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 19,
                            Category = "Pizzor",
                            Description = "Bacon, Champinjoner, Lök, Paprika",
                            MenuNumber = 15,
                            Name = "Mama Mia",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 20,
                            Category = "Pizzor",
                            Description = "Fläskfilé, Lök, Champinjoner, Bearnaisesås",
                            MenuNumber = 16,
                            Name = "Amore Mio",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 21,
                            Category = "Pizzor",
                            Description = "Fläskfilé, Lök, Champinjoner, Vitlökssås (Inbakad)",
                            MenuNumber = 17,
                            Name = "Ciao Ciao",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 22,
                            Category = "Pizzor",
                            Description = "Skinka, Ananas, Räkor",
                            MenuNumber = 18,
                            Name = "Prinsessa",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 23,
                            Category = "Pizzor",
                            Description = "Skinka, Bacon, Lök, Bearnaisesås",
                            MenuNumber = 19,
                            Name = "Papillon",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 24,
                            Category = "Pizzor",
                            Description = "Kyckling, Ananas, Jordnötter, Curry",
                            MenuNumber = 20,
                            Name = "Kycklingpizza",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 25,
                            Category = "Pizzor",
                            Description = "Champinjoner, Ananas, Paprika, Lök, Tomat, Sparris",
                            MenuNumber = 21,
                            Name = "Vegetariana",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 26,
                            Category = "Pizzor",
                            Description = "Kebabkött, Lök, Kebabsås",
                            MenuNumber = 22,
                            Name = "Kebabpizza",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 27,
                            Category = "Pizzor",
                            Description = "Champinjoner, Oxfilé, Gorgonzolaost",
                            MenuNumber = 23,
                            Name = "Gorgonzola",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 28,
                            Category = "Pizzor",
                            Description = "Skinka, Köttfärssås",
                            MenuNumber = 24,
                            Name = "Disco",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 29,
                            Category = "Pizzor",
                            Description = "Skinka, Kebabkött, Champinjoner, Bearnaisesås",
                            MenuNumber = 25,
                            Name = "Rolandpizza",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 30,
                            Category = "Pizzor",
                            Description = "Kebabkött, Lök, Paprika, Champinjoner, Kebabsås",
                            MenuNumber = 26,
                            Name = "Alexpizza",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 31,
                            Category = "Pizzor",
                            Description = "Kebabkött, Lök, Paprika, Stark kebabsås, Vitlökssås",
                            MenuNumber = 27,
                            Name = "Cyckelpizza",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 32,
                            Category = "Pizzor",
                            Description = "Oxfilé, Champinjoner, Sparris, Bearnaisesås",
                            MenuNumber = 28,
                            Name = "Husets pizza",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 33,
                            Category = "Pizzor",
                            Description = "Skinka, Musslor, Räkor, Champinjoner",
                            MenuNumber = 29,
                            Name = "Quatro Stagioni",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 34,
                            Category = "Pizzor",
                            Description = "Köttfärssås, Champinjoner, Lök, Tacosås, Vitlökssås",
                            MenuNumber = 30,
                            Name = "Mexicana",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 35,
                            Category = "Pizzor",
                            Description = "Skinka, Tacosås, Jalapeno, Lök, Vitlökssås",
                            MenuNumber = 31,
                            Name = "Azteka",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 36,
                            Category = "Pizzor",
                            Description = "Oxfilé, Champinjoner, Lök, Jalapeno, Tacosås, Vitlökssås",
                            MenuNumber = 32,
                            Name = "Acapulko",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 37,
                            Category = "Pizzor",
                            Description = "Kebabkött, Gurka, Tomat, Isbergssallad, Kebabsås, Lök",
                            MenuNumber = 33,
                            Name = "Kebabspecial",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 38,
                            Category = "Pizzor",
                            Description = "Kebabkött, Skinka, Pommes, Kebabsås",
                            MenuNumber = 34,
                            Name = "Vara Special",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 39,
                            Category = "Pizzor",
                            Description = "Kebabkött, Skinka, Ananas, Kebabsås",
                            MenuNumber = 35,
                            Name = "Tre Kronor",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 40,
                            Category = "Pizzor",
                            Description = "Fläskfilé, Champinjoner, Paprika, Lök, Bearnaisesås (Dubbel inbakad)",
                            MenuNumber = 36,
                            Name = "Flygande Tefat",
                            Price = 100m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 41,
                            Category = "Pizzor",
                            Description = "Fläskfilé, Champinjoner, Paprika, Lök, Bearnaisesås (Halvt inbakad)",
                            MenuNumber = 37,
                            Name = "U-båt 1",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 42,
                            Category = "Pizzor",
                            Description = "Skinka, Kebabkött, Champinjoner, Kebabsås (Halvt inbakad)",
                            MenuNumber = 38,
                            Name = "U-båt 2",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 43,
                            Category = "Pizzor",
                            Description = "Kyckling, Räkor, Champinjoner, Lök, Paprika, Kebabsås",
                            MenuNumber = 39,
                            Name = "Kycklinggryta",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 44,
                            Category = "Pizzor",
                            Description = "Kebabkött, Skinka, Räkor, Ananas, Champinjoner, Kebabsås",
                            MenuNumber = 40,
                            Name = "Frank Special",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 45,
                            Category = "Pizzor",
                            Description = "Skinka, Kebabkött, Bacon, Champinjoner, Kebabsås",
                            MenuNumber = 41,
                            Name = "Kvänums Special",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 46,
                            Category = "Pizzor",
                            Description = "Skinka, Lök, Paprika, Champinjoner, Kebabkött, Kebabsås",
                            MenuNumber = 42,
                            Name = "Anderspizza",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 47,
                            Category = "Pizzor",
                            Description = "Skinka, Champinjoner, Köttfärs, Pommes, Kebabsås",
                            MenuNumber = 43,
                            Name = "Curuso Special",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 48,
                            Category = "Sallader",
                            Description = "Skinka, Räkor, Ananas, Ost, Sallad, Gurka, Majs",
                            Name = "Amerikansk Sallad",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 49,
                            Category = "Sallader",
                            Description = "Räkor, Ost, Ägg, Citron, Tomat, Sallad, Gurka, Majs",
                            Name = "Räksallad",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 50,
                            Category = "Sallader",
                            Description = "Räkor, Musslor, Champinjoner, Majs, Citron, Tomat, Sallad, Gurka",
                            Name = "Västkustsallad",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 51,
                            Category = "Sallader",
                            Description = "Kyckling, Ananas, Majs, Tomat, Sallad, Gurka",
                            Name = "Kycklingsallad",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 52,
                            Category = "Sallader",
                            Description = "Tonfisk, Ost, Lök, Majs, Champinjoner, Tomat, Sallad, Gurka",
                            Name = "Tonfisksallad",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 53,
                            Category = "Sallader",
                            Description = "Kebab, Lök, Majs, Champinjoner, Tomat, Sallad, Gurka",
                            Name = "Kebabsallad",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 54,
                            Category = "Sallader",
                            Description = "Nötfärs, Majs, Lök, Ost, Ananas, Tomat, Gurka, Sallad, Tacosås",
                            Name = "Tacosallad",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 55,
                            Category = "Sallader",
                            Description = "Sallad, Gurka, Ananas, Champinjoner, Paprika, Majs, Sparris",
                            Name = "Vegetarisk Sallad",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 56,
                            Category = "Kebab",
                            Description = "Kebab eller kyckling, Sallad, Tomat, Gurka, Lök, Kebabsås",
                            Name = "Kebab m. Bröd",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 57,
                            Category = "Kebab",
                            Description = "Pommes, Sallad, Gurka, Tomat, Lök, Kebabsås",
                            Name = "Kebab/Kyckling-Tallrik",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 58,
                            Category = "Kebab",
                            Description = "Kebab eller kyckling, Sallad, Tomat, Gurka, Lök, Kebabsås",
                            Name = "Kebab/Kyckling-Rulle",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 59,
                            Category = "Kebab",
                            Description = "Räkor, Sallad, Gurka, Tomat, Skinka, Ananas, Kebabsås",
                            Name = "Räkrulle",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 60,
                            Category = "Kebab",
                            Description = "Skinka, Sallad, Gurka, Tomat, Ananas, Kebabsås",
                            Name = "Hawaiirulle",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 61,
                            Category = "Kebab",
                            Description = "Nötfärs, Majs, Lök, Gurka, Tomat, Sallad, Tacosås, Jalapeno",
                            Name = "Tacorulle",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 62,
                            Category = "Kebab",
                            Description = "Med potatismos, Kebabsås",
                            Name = "Kebabtallrik",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 63,
                            Category = "Kebab",
                            Description = "Kebab, Pommes, Kebabsås",
                            Name = "Kebabrulle",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 64,
                            Category = "Kebab",
                            Description = "Kyckling, Pommes, Kebabsås",
                            Name = "Kycklingrulle",
                            Price = 90m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 65,
                            Category = "Stekrätter",
                            Description = "Med bröd & Pommes",
                            Name = "Hamburgare 90gr",
                            Price = 80m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "",
                            Description = "",
                            Name = "Oxfilé med potatis",
                            Price = 189m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = "",
                            Description = "",
                            Name = "Kycklingfilé",
                            Price = 159m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 7,
                            Category = "",
                            Description = "",
                            Name = "Pasta Carbonara",
                            Price = 149m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "",
                            Description = "",
                            Name = "Caesarsallad",
                            Price = 139m,
                            RestaurantId = 2
                        });
                });

            modelBuilder.Entity("PizzaApp.Api.Models.PizzaOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCollect")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Drink")
                        .HasColumnType("text");

                    b.Property<int?>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pizza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Sauce")
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("RestaurantId", "OrderDate");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaApp.Api.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPizzeria")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPizzeria = true,
                            Name = "Kvänum Pizzeria"
                        },
                        new
                        {
                            Id = 2,
                            IsPizzeria = false,
                            Name = "Sperring"
                        });
                });

            modelBuilder.Entity("PizzaApp.Api.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AliasKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AvatarDataUrl")
                        .HasMaxLength(350000)
                        .HasColumnType("character varying(350000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsRegisteredMember")
                        .HasColumnType("boolean");

                    b.Property<string>("LoginEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("AliasKey")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("PizzaApp.Api.Models.CompletedOrderDay", b =>
                {
                    b.HasOne("PizzaApp.Api.Models.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Api.Models.MenuItem", b =>
                {
                    b.HasOne("PizzaApp.Api.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("PizzaApp.Api.Models.PizzaOrder", b =>
                {
                    b.HasOne("PizzaApp.Api.Models.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PizzaApp.Api.Models.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PizzaApp.Api.Models.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
