// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaApp.Api.Data;

#nullable disable

namespace PizzaApp.Api.Migrations
{
    [DbContext(typeof(PizzaDbContext))]
    [Migration("20260924200755_InvitationRegistration")]
    partial class InvitationRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PizzaApp.Api.Models.CompletedOrderDay", b =>
                {
                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CollectorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPizzeria")
                        .HasColumnType("boolean");

                    b.Property<string>("OrdersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RestaurantId", "Date");

                    b.ToTable("CompletedOrderDays");
                });

            modelBuilder.Entity("PizzaApp.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Margharita",
                            Price = 95m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vesuvio",
                            Price = 95m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Capricciosa",
                            Price = 95m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hawaii",
                            Price = 95m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Oxfilé med potatis",
                            Price = 189m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kycklingfilé",
                            Price = 159m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pasta Carbonara",
                            Price = 149m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Caesarsallad",
                            Price = 139m,
                            RestaurantId = 2
                        });
                });

            modelBuilder.Entity("PizzaApp.Api.Models.PizzaOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCollect")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Drink")
                        .HasColumnType("text");

                    b.Property<int?>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pizza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Sauce")
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("RestaurantId", "OrderDate");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaApp.Api.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPizzeria")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPizzeria = true,
                            Name = "Kvänum Pizzeria"
                        },
                        new
                        {
                            Id = 2,
                            IsPizzeria = false,
                            Name = "Sperring"
                        });
                });

            modelBuilder.Entity("PizzaApp.Api.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarDataUrl")
                        .HasMaxLength(350000)
                        .HasColumnType("character varying(350000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsRegisteredMember")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("PizzaApp.Api.Models.CompletedOrderDay", b =>
                {
                    b.HasOne("PizzaApp.Api.Models.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Api.Models.MenuItem", b =>
                {
                    b.HasOne("PizzaApp.Api.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("PizzaApp.Api.Models.PizzaOrder", b =>
                {
                    b.HasOne("PizzaApp.Api.Models.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PizzaApp.Api.Models.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PizzaApp.Api.Models.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
